
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - dock_net
    volumes:
      - wordpress:/var/www/html
  web:
    container_name: django
    build: 
      context: ./django:/data
    ports:
      - "8000:8000"
    networks:
      - dock_net
    volumes:
      - django
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    networks:
      - dock_net
    env_file:
      - .env

networks:
  dock_net:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: "./srcs/redis/src"
      o: bind
  postgres:
    driver: local
    driver_opts:
      type: none
      device: "./srcs/postgre/src"
      o: bind
  django:
    driver: local
    driver_opts:
      type: none
      device: "./srcs/django/src"
      o: bind