
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "40043:40043"
    networks:
      - dock_net
    volumes:
      - nginx:/usr/
  web:
    container_name: django
    build: 
      context: ./django
    ports:
      - "8000:8000"
    networks:
      - dock_net
    volumes:
      - django:/usr/
  database:
    container_name: postgres
    image: postgres:17.2-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dock_net
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  dock_net:
    driver: bridge

volumes:
  nginx:
    name: "nginx"
    driver: local
    driver_opts:
      type: none
      device: "./nginx"
      o: bind
  postgres:
    name: "postgres"
    driver: local
    driver_opts:
      type: none
      device: "./postgres"
      o: bind
  django:
    name: "django"
    driver: local
    driver_opts:
      type: none
      device: "./django"
      o: bind